name: "Optimize resource pack"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Optimize resource pack"
    runs-on: "ubuntu-latest"

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4.0.2
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'pack'
            zip_spec_conformance_level = 'disregard'
            output_file_path = '/tmp/pack.zip'
      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: action-v${{ github.run_number }}
          files: /tmp/pack.zip
