name: "Optimize resource pack"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Optimize resource pack"
    runs-on: "ubuntu-latest"

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4.0.2
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'pack'
            zip_spec_conformance_level = 'disregard'
      - name: Download optimized pack
        uses: actions/download-artifact@v4
        with:
          name: Optimized pack
      - name: Publish release 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            pack.zip
